# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dezero2',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/dezero2',
                'lib_path': 'dezero2'},
  'syms': {'dezero2.core': {'dezero2.core.foo': ('core.html#foo', 'dezero2/core.py')}}}
